from typing import List, Optional
from typing_extensions import Protocol
from src.core.domain.event import Event

class EventRepository(Protocol):
    async def create(self, event: Event) -> Event: ...
    async def list_by_match(self, match_id: str) -> List[Event]: ...
    async def delete_last_by_match(self, match_id: str) -> bool: ...
