from typing import List, Optional
from typing_extensions import Protocol
from src.core.domain.match import Match

class MatchRepository(Protocol):
    async def create(self, match: Match) -> Match: ...
    async def get_by_id(self, match_id: str) -> Optional[Match]: ...
    async def list_all(self, skip: int = 0, limit: int = 50) -> List[Match]: ...
    async def update(self, match_id: str, match_data: dict) -> Optional[Match]: ...
    async def delete(self, match_id: str) -> bool: ...
