from typing import List, Optional
from typing_extensions import Protocol
from src.core.domain.player import Player

class PlayerRepository(Protocol):
    async def create(self, player: Player) -> Player: ...
    async def list_by_match(self, match_id: str, team: Optional[str] = None) -> List[Player]: ...
    async def get_by_id(self, match_id: str, player_id: str) -> Optional[Player]: ...
    async def update(self, match_id: str, player_id: str, player_data: dict) -> Optional[Player]: ...
    async def delete(self, match_id: str, player_id: str) -> bool: ...
    async def create_many(self, players: List[Player]) -> List[Player]: ...
